### ISSUE TITLE
[提问]大佬好，我在运行程序之后发生了如下的报错，请问如何解决呢？

### ISSUE THREAD

**Issue by ifhjl** [wxc971231/RL_Platform-CrossTheWall#1]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by wxc971231** [comment]
> 
你好，这个报错是 pyqt5 没有正确安装导致的，可以直接百度这个报错看一下怎么修复。我建议使用 anaconda 创建虚拟环境，再用 pip 安装 pyqt5

**Comment by wxc971231** [comment]
由于长时间未收到您的回复，默认问题已经解决

**Comment by wxc971231** [comment]
由于长时间未收到您的回复，默认问题已经解决
